title: Software Development ePortfolio
description: Welcome to My Software Development ePortfolio
remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-hacker
plugins:
- jekyll-remote-themep
github:
  is_project_page: false
show_downloads: false

