title: Software Development ePortfolio
description: Welcome to My Software Development ePortfolio
baseurl: "" # Keep this blank unless your site is in a subdirectory
url: ""     # Add your site URL if deploying
theme: null
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links

defaults:
  - scope:
      path: ""
    values:
      layout: default
      permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
